version: 2
updates:
  # Cấu hình Dependabot quét Backend (UV/Pip)
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
    allow:
      - dependency-type: "all"
        update-types:
          - "version-update:semver-minor"
          - "version-update:semver-patch"
    commit-message:
      prefix: "chore(backend)"
    labels:
      - "dependencies"
      - "python"

  # Cấu hình Dependabot quét Frontend (NPM)
  - package-ecosystem: "npm"
    directory: "/frontend"
    schedule:
      interval: "weekly"
    allow:
      - dependency-type: "all"
        update-types:
          - "version-update:semver-minor"
          - "version-update:semver-patch"
    commit-message:
      prefix: "chore(frontend)"
    labels:
      - "dependencies"
      - "npm"
