FROM node:22-alpine

WORKDIR /app/frontend

# Install pnpm and dependencies
RUN corepack enable
COPY package.json pnpm-lock.yaml ./
RUN pnpm install --no-frozen-lockfile

# Copy the rest of the code
COPY . .

EXPOSE 5173

# Default command for dev
CMD ["pnpm", "dev", "--host", "0.0.0.0"]
