
import sys
import os
sys.path.append(os.getcwd())

from backend.services.xohi.creative_studio.utils.stitcher import surgical_stitch
import logging

# Setup logging to see the "Neural Fuzzy" logic in action
logging.basicConfig(level=logging.INFO)

content = """
<p>Sở hữu bảng thành phần đột phá với hàm lượng <strong>Placenta</strong> nồng độ cao, <strong>Miccosmo Beppin Body Virgin White Serum 30g</strong> chính là "trợ thủ" đắc lực đã được hơn 92% chuyên gia da liễu Nhật Bản khuyên dùng, giúp tối ưu hóa hiệu quả ức chế sắc tố melanin tới 85% tại các vùng nhạy cảm chỉ trong chu kỳ tái tạo 14 ngày., giúp giải quyết tình trạng thâm sạm – Giải pháp chuyên biệt từ thương hiệu Miccosmo Nhật Bản giúp giải quyết hiệu quả tình trạng thâm sạm và xỉn màu.</p>
"""

# The snippet identified by the AI (plain text, might have minor mismatches)
old_snippet = "Sở hữu bảng thành phần đột phá với hàm lượng Placenta nồng độ cao, Miccosmo Beppin Body Virgin White Serum 30g chính là \"trợ thủ\" đắc lực đã được hơn 92% chuyên gia da liễu Nhật Bản khuyên dùng, giúp tối ưu hóa hiệu quả ức chế sắc tố melanin tới 85% tại các vùng nhạy cảm chỉ trong chu kỳ tái tạo 14 ngày., giúp giải quyết tình trạng thâm sạm – Giải pháp chuyên biệt từ thương hiệu Miccosmo Nhật Bản giúp giải quyết hiệu quả tình trạng thâm sạm và xỉn màu."

# The new, honest text generated by the AI (removing fake percentages and adding Information Gain)
new_snippet = "Sở hữu bảng thành phần đột phá với hàm lượng Placenta cô đặc, Miccosmo Beppin Body Virgin White Serum 30g là giải pháp dưỡng sáng chuyên sâu đã qua kiểm nghiệm lâm sàng, hỗ trợ ức chế sản sinh hắc sắc tố melanin tại các vùng da nhạy cảm. Sản phẩm giúp phục hồi độ sáng tự nhiên, giải quyết tình trạng thâm sạm và xỉn màu nhờ công thức Nhật Bản độc quyền, mang lại làn da mịn màng và đều màu sau lộ trình sử dụng đều đặn."

print("--- [ORIGINAL HTML] ---")
print(content)

print("\n--- [APPLYING SURGICAL FIX...] ---")
updated_content = surgical_stitch(content, old_snippet, new_snippet)

print("\n--- [UPDATED HTML] ---")
print(updated_content)

if updated_content != content:
    print("\n✅ SUCCESS: Surgical fix applied perfectly even through HTML tags!")
else:
    print("\n❌ FAILED: Surgical fix could not match the snippet.")
