import os

# R101: Concurrency Limits
ORCHESTRATOR_SEMAPHORE_LIMIT = int(os.getenv("ORCHESTRATOR_SEMAPHORE_LIMIT", "3"))

# R82.8: Perception Latency
STEP_ARTIFICIAL_LATENCY_SECONDS = float(os.getenv("STEP_ARTIFICIAL_LATENCY_SECONDS", "1.5"))

# R106: HTTP Client Limits
HTTP_MAX_CONNECTIONS = 100
HTTP_KEEPALIVE_CONNECTIONS = 20
HTTP_TIMEOUT_SECONDS = 30.0

# V61.0: Viral Cache Config
CONTENT_CACHE_MAXSIZE = 200
CONTENT_CACHE_TTL = 60 # 1 minute for hot state

# Campaign Config
MAX_SEARCH_RETRY_PER_STEP = 3
SEARCH_CIRCUIT_BREAKER_COOLDOWN_MINUTES = 15
