import type { WidgetType } from "./types";

export const COMMAND_WIDGET_MAP: Record<string, WidgetType> = {
  "manage orders": "ORDER_MANAGEMENT",
  "mở đơn hàng": "ORDER_MANAGEMENT",
  "đơn hàng": "ORDER_MANAGEMENT",
  "manage products": "PRODUCT_MANAGEMENT",
  "mở sản phẩm": "PRODUCT_MANAGEMENT",
  "sản phẩm": "PRODUCT_MANAGEMENT",
  "manage categories": "CATEGORY_MANAGEMENT",
  "mở danh mục": "CATEGORY_MANAGEMENT",
  "danh mục": "CATEGORY_MANAGEMENT",
  "manage users": "USER_MANAGEMENT",
  "mở người dùng": "USER_MANAGEMENT",
  "người dùng": "USER_MANAGEMENT",
  "manage permissions": "PERMISSION_MANAGEMENT",
  "mở phân quyền": "PERMISSION_MANAGEMENT",
  "phân quyền": "PERMISSION_MANAGEMENT",
  "manage news": "NEWS_MANAGEMENT",
  "mở Bài viết": "NEWS_MANAGEMENT",
  "Bài viết": "NEWS_MANAGEMENT",
  "manage banners": "BANNER_MANAGEMENT",
  "mở banner": "BANNER_MANAGEMENT",
  "banner": "BANNER_MANAGEMENT",
  "manage reviews": "REVIEW_MANAGEMENT",
  "mở đánh giá": "REVIEW_MANAGEMENT",
  "đánh giá": "REVIEW_MANAGEMENT",
  "manage appointments": "APPOINTMENTS",
  "mở lịch hẹn": "APPOINTMENTS",
  "lịch hẹn": "APPOINTMENTS",
  "manage media": "MEDIA_MANAGER",
  "mở thư viện": "MEDIA_MANAGER",
  "thư viện ảnh": "MEDIA_MANAGER",

  skill: "VOICE_SETTINGS",
  "voice settings": "VOICE_SETTINGS",
  "mở cài đặt giọng": "VOICE_SETTINGS",
  "mở cài đặt": "SYSTEM_SETTINGS",
  "mở cấu hình": "SYSTEM_SETTINGS",
  "cấu hình hệ thống": "SYSTEM_SETTINGS",
  "manage skills": "VOICE_SETTINGS",
  "skills": "VOICE_SETTINGS",
  "campaigns": "CAMPAIGNS",
  "content factory": "CAMPAIGNS",
  "mở campaigns": "CAMPAIGNS",
  "mở chiến dịch": "CAMPAIGNS",
  "chiến dịch": "CAMPAIGNS",
  "quản lý chiến dịch": "CAMPAIGNS",
  "open campaign": "CAMPAIGNS",
  "support knowledge": "SUPPORT_KNOWLEDGE",
  "helen brain": "SUPPORT_KNOWLEDGE",
  "đào tạo helen": "SUPPORT_KNOWLEDGE",
  "mở tri thức helen": "SUPPORT_KNOWLEDGE",
  "mở helen": "SUPPORT_KNOWLEDGE",
  "manage support": "SUPPORT_INBOX",
  "mở inbox": "SUPPORT_INBOX",
  "hộp thư": "SUPPORT_INBOX",
  "hàng đợi": "SUPPORT_INBOX",
  "mở brain": "BRAIN_MANAGEMENT",
  "brain": "BRAIN_MANAGEMENT",
  "quản trị tri thức": "BRAIN_MANAGEMENT",
  "mở voucher": "VOUCHER_MANAGEMENT",
  "voucher": "VOUCHER_MANAGEMENT",
  "khuyến mãi": "VOUCHER_MANAGEMENT",
  "mã giảm giá": "VOUCHER_MANAGEMENT",
  "manage ctv": "CTV_MANAGEMENT",
  "mở ctv": "CTV_MANAGEMENT",
  "quản lý ctv": "CTV_MANAGEMENT",
  "manage signals": "NOTIFICATION_MANAGEMENT",
  "mở tín hiệu": "NOTIFICATION_MANAGEMENT",
  "tín hiệu": "NOTIFICATION_MANAGEMENT",
  "mở chuông": "NOTIFICATION_MANAGEMENT",
  "chuông": "NOTIFICATION_MANAGEMENT",
  "notification": "NOTIFICATION_MANAGEMENT",
  "mở thông báo": "NOTIFICATION_MANAGEMENT",
  "thông báo": "NOTIFICATION_MANAGEMENT",
  "quản lý thông báo": "NOTIFICATION_MANAGEMENT",
  "mở seo graph": "SEO_GRAPH",
  "seo graph": "SEO_GRAPH",
  "mở mạng lưới seo": "SEO_GRAPH",
  "mạng lưới seo": "SEO_GRAPH",
  "mở duyệt link sge": "SEO_LINK_REVIEW",
  "duyệt link sge": "SEO_LINK_REVIEW",
  "duyệt link": "SEO_LINK_REVIEW",
  "mở duyệt link": "SEO_LINK_REVIEW",
  "seo link review": "SEO_LINK_REVIEW",
  "ads protection": "ADS_PROTECTION",
  "click tặc": "ADS_PROTECTION",
  "click tac": "ADS_PROTECTION",
  "pháp y": "ADS_PROTECTION",
  "phap y": "ADS_PROTECTION",
  "báo cáo info": "ADS_PROTECTION",
  "bao cao info": "ADS_PROTECTION",
  "báo cáo": "ADS_PROTECTION",
  "bao cao": "ADS_PROTECTION",
  "mở quảng cáo": "ADS_PROTECTION",
  "mở báo cáo": "ADS_PROTECTION",
  "mở pháp y": "ADS_PROTECTION",
  "kịch bản video": "VIDEO_SCRIPT_MANAGEMENT",
  "mở kịch bản": "VIDEO_SCRIPT_MANAGEMENT",
  "video script": "VIDEO_SCRIPT_MANAGEMENT",
  "quản lý kịch bản": "VIDEO_SCRIPT_MANAGEMENT",
};

export const ACTION_WIDGET_MAP: Record<string, WidgetType> = {
  CONTENT_CREATE: "CONTENT_REVIEW",
  show_revenue_chart: "REVENUE_CHART",
  show_revenue: "SHOW_REVENUE",
  show_product_edit: "SHOW_PRODUCT_EDIT",
  show_user_table: "USER_TABLE",
  show_user_management: "USER_MANAGEMENT",
  show_category_management: "CATEGORY_MANAGEMENT",
  show_product_management: "PRODUCT_MANAGEMENT",
  show_order_management: "ORDER_MANAGEMENT",
  show_news_management: "NEWS_MANAGEMENT",
  show_permission_management: "PERMISSION_MANAGEMENT",
  show_voice_settings: "VOICE_SETTINGS",
  show_skills: "VOICE_SETTINGS",
  show_campaigns: "CAMPAIGNS",
  show_content_factory: "CAMPAIGNS",
  show_support_knowledge: "SUPPORT_KNOWLEDGE",
  show_system_settings: "SYSTEM_SETTINGS",
  show_banner_management: "BANNER_MANAGEMENT",
  show_review_management: "REVIEW_MANAGEMENT",
  show_appointment_management: "APPOINTMENTS",
  show_media_manager: "MEDIA_MANAGER",
  show_support_inbox: "SUPPORT_INBOX",
  show_brain: "BRAIN_MANAGEMENT",
  show_voucher_management: "VOUCHER_MANAGEMENT",
  show_ctv_management: "CTV_MANAGEMENT",
  show_notification_management: "NOTIFICATION_MANAGEMENT",
  show_seo_graph: "SEO_GRAPH",
  show_seo_link_review: "SEO_LINK_REVIEW",
  show_ads_protection: "ADS_PROTECTION",
  show_video_script_management: "VIDEO_SCRIPT_MANAGEMENT",
};

export const WIDGET_VI_LABEL: Record<string, string> = {
  ORDER_MANAGEMENT: "Quản lý Đơn hàng",
  PRODUCT_MANAGEMENT: "Quản lý Sản phẩm",
  CATEGORY_MANAGEMENT: "Quản lý Danh mục",
  USER_MANAGEMENT: "Quản lý Người dùng",
  PERMISSION_MANAGEMENT: "Phân quyền Hệ thống",
  NEWS_MANAGEMENT: "Quản lý Bài viết",
  VOICE_SETTINGS: "Cài đặt Giọng nói",
  CAMPAIGNS: "Content Factory",
  CONTENT_REVIEW: "Trình Duyệt Bài Viết",
  SUPPORT_KNOWLEDGE: "Đào tạo Helen AI",
  SYSTEM_SETTINGS: "Cấu hình Hệ thống",
  BANNER_MANAGEMENT: "Quản lý Banner",
  REVIEW_MANAGEMENT: "Quản lý Đánh giá",
  APPOINTMENTS: "Quản lý Lịch hẹn",
  MEDIA_MANAGER: "Thư viện Ảnh",
  REVENUE_CHART: "Biểu đồ Doanh thu",
  SUPPORT_INBOX: "Hộp thư Helen AI",
  BRAIN_MANAGEMENT: "HELEN BRAIN — QUẢN TRỊ TRI THỨC",
  VOUCHER_MANAGEMENT: "Quản lý Voucher & Khuyến mãi",
  CTV_MANAGEMENT: "Quản lý Hệ thống Liên kết (CTV)",
  NOTIFICATION_MANAGEMENT: "Quản trị Tín hiệu & Thông báo",
  SEO_GRAPH: "Mạng lưới SEO Graph",
  SEO_LINK_REVIEW: "Duyệt liên kết ngữ cảnh SGE",
  VIDEO_SCRIPT_MANAGEMENT: "Kịch bản Video Marketing",
};
