"""create_media_registry_table

Revision ID: 0bd3805cd8a3
Revises: 9f4bd635a9b4
Create Date: 2026-03-15 17:21:14.348834

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0bd3805cd8a3'
down_revision: Union[str, Sequence[str], None] = '9f4bd635a9b4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('media_registry',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('filename', sa.String(), nullable=False),
    sa.Column('file_path', sa.String(), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=False),
    sa.Column('mime_type', sa.String(length=50), nullable=False),
    sa.Column('dimensions', sa.String(length=20), nullable=True),
    sa.Column('blurhash', sa.String(length=100), nullable=True),
    sa.Column('alt_text', sa.String(), nullable=True),
    sa.Column('campaign_id', sa.String(), nullable=True),
    sa.Column('owner_id', sa.String(), nullable=True),
    sa.Column('media_metadata', sa.JSON(), nullable=False),
    sa.Column('provider', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('tenant_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['campaign_id'], ['content_campaigns.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('file_path')
    )
    op.create_index('ix_media_campaign_provider', 'media_registry', ['campaign_id', 'provider'], unique=False)
    op.create_index(op.f('ix_media_registry_campaign_id'), 'media_registry', ['campaign_id'], unique=False)
    op.create_index(op.f('ix_media_registry_filename'), 'media_registry', ['filename'], unique=False)
    op.create_index(op.f('ix_media_registry_owner_id'), 'media_registry', ['owner_id'], unique=False)
    op.create_index(op.f('ix_media_registry_tenant_id'), 'media_registry', ['tenant_id'], unique=False)
    op.create_index('ix_media_tenant_deleted', 'media_registry', ['tenant_id', 'deleted_at'], unique=False)
    op.drop_index(op.f('ix_content_campaigns_category'), table_name='content_campaigns')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_content_campaigns_category'), 'content_campaigns', ['category'], unique=False)
    op.drop_index('ix_media_tenant_deleted', table_name='media_registry')
    op.drop_index(op.f('ix_media_registry_tenant_id'), table_name='media_registry')
    op.drop_index(op.f('ix_media_registry_owner_id'), table_name='media_registry')
    op.drop_index(op.f('ix_media_registry_filename'), table_name='media_registry')
    op.drop_index(op.f('ix_media_registry_campaign_id'), table_name='media_registry')
    op.drop_index('ix_media_campaign_provider', table_name='media_registry')
    op.drop_table('media_registry')
    # ### end Alembic commands ###
