"""Add discount_percent to products and variants

Revision ID: 106081ae8dbf
Revises: 4507a49139ff
Create Date: 2026-04-22 14:57:11.128897

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '106081ae8dbf'
down_revision: Union[str, Sequence[str], None] = '4507a49139ff'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product_bases', schema=None) as batch_op:
        batch_op.add_column(sa.Column('discount_percent', sa.Float(), nullable=True))

    with op.batch_alter_table('product_variants', schema=None) as batch_op:
        batch_op.add_column(sa.Column('discount_percent', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product_variants', schema=None) as batch_op:
        batch_op.drop_column('discount_percent')

    with op.batch_alter_table('product_bases', schema=None) as batch_op:
        batch_op.drop_column('discount_percent')

    # ### end Alembic commands ###
