"""professional_fashion_upgrade

Revision ID: 11e257eec77c
Revises: c9927d9a523b
Create Date: 2026-03-20 05:12:34.094327

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '11e257eec77c'
down_revision: Union[str, Sequence[str], None] = 'c9927d9a523b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('categories', sa.Column('description', sa.Text(), nullable=True))
    op.add_column('categories', sa.Column('seo_title', sa.String(), nullable=True))
    op.add_column('categories', sa.Column('seo_description', sa.String(), nullable=True))
    op.add_column('categories', sa.Column('image', sa.String(), nullable=True))
    
    # R102: Handle existing data by adding nullable column first
    op.add_column('product_bases', sa.Column('slug', sa.String(), nullable=True))
    op.execute("UPDATE product_bases SET slug = id WHERE slug IS NULL")
    op.alter_column('product_bases', 'slug', nullable=False)
    
    op.add_column('product_bases', sa.Column('seo_title', sa.String(), nullable=True))
    op.add_column('product_bases', sa.Column('seo_description', sa.String(), nullable=True))
    op.add_column('product_bases', sa.Column('images', sa.JSON(), nullable=True))
    op.add_column('product_bases', sa.Column('attributes', sa.JSON(), nullable=True))
    op.create_index(op.f('ix_product_bases_slug'), 'product_bases', ['slug'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_product_bases_slug'), table_name='product_bases')
    op.drop_column('product_bases', 'attributes')
    op.drop_column('product_bases', 'images')
    op.drop_column('product_bases', 'seo_description')
    op.drop_column('product_bases', 'seo_title')
    op.drop_column('product_bases', 'slug')
    op.drop_column('categories', 'image')
    op.drop_column('categories', 'seo_description')
    op.drop_column('categories', 'seo_title')
    op.drop_column('categories', 'description')
    # ### end Alembic commands ###
