"""add_attributes_to_product_variants

Revision ID: 1479be76e57a
Revises: 71037d3028b2
Create Date: 2026-04-17 16:53:32.772081

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1479be76e57a'
down_revision: Union[str, Sequence[str], None] = '71037d3028b2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product_variants', schema=None) as batch_op:
        batch_op.add_column(sa.Column('attributes', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product_variants', schema=None) as batch_op:
        batch_op.drop_column('attributes')

    # ### end Alembic commands ###
