"""Add ads protection tables

Revision ID: 19c1873b85a8
Revises: 9e67322e3952
Create Date: 2026-05-11 22:27:45.315494

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '19c1873b85a8'
down_revision: Union[str, Sequence[str], None] = '9e67322e3952'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ads_ip_blacklist',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ip_address', sa.String(length=45), nullable=False),
    sa.Column('reason', sa.String(length=256), nullable=True),
    sa.Column('fraud_score', sa.Float(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('country', sa.String(length=8), nullable=True),
    sa.Column('org', sa.String(length=128), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ads_ip_blacklist', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ads_ip_blacklist_ip_address'), ['ip_address'], unique=True)

    op.create_table('ads_negative_keywords',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('campaign_id', sa.String(length=64), nullable=True),
    sa.Column('keyword_text', sa.String(length=256), nullable=False),
    sa.Column('match_type', sa.String(length=16), nullable=False),
    sa.Column('is_synced', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ads_negative_keywords', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ads_negative_keywords_campaign_id'), ['campaign_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ads_negative_keywords', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ads_negative_keywords_campaign_id'))

    op.drop_table('ads_negative_keywords')
    with op.batch_alter_table('ads_ip_blacklist', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ads_ip_blacklist_ip_address'))

    op.drop_table('ads_ip_blacklist')
    # ### end Alembic commands ###
