"""Add gemini_keys_enc to VoiceProfile

Revision ID: 20b368eb59d0
Revises: 994c68ed3a6c
Create Date: 2026-03-13 00:26:38.963980

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '20b368eb59d0'
down_revision: Union[str, Sequence[str], None] = '994c68ed3a6c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('voice_profiles', sa.Column('gemini_keys_enc', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('voice_profiles', 'gemini_keys_enc')
    # ### end Alembic commands ###
