"""make_variant_sku_nullable

Revision ID: 24da2393a26a
Revises: 70e7b7bd1213
Create Date: 2026-03-26 15:47:51.430454

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '24da2393a26a'
down_revision: Union[str, Sequence[str], None] = '70e7b7bd1213'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product_variants', schema=None) as batch_op:
        batch_op.alter_column('sku',
               nullable=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product_variants', schema=None) as batch_op:
        batch_op.alter_column('sku',
               nullable=False)

    # ### end Alembic commands ###
