"""add_ai_featured_to_product

Revision ID: 29ceb4ebe528
Revises: 7d2c1763ceb5
Create Date: 2026-04-10 14:13:52.271381

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '29ceb4ebe528'
down_revision: Union[str, Sequence[str], None] = '7d2c1763ceb5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
