"""add_reasoning_to_ads

Revision ID: 3114a9cfe427
Revises: e9b07d35313a
Create Date: 2026-05-12 16:28:51.604723

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3114a9cfe427'
down_revision: Union[str, Sequence[str], None] = 'e9b07d35313a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('click_fraud_events', schema=None) as batch_op:
        batch_op.add_column(sa.Column('reasoning', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('click_fraud_events', schema=None) as batch_op:
        batch_op.drop_column('reasoning')

    # ### end Alembic commands ###
