"""add_analysis_report_to_articles_and_products

Revision ID: 32d16cea1275
Revises: c504a40ccdd3
Create Date: 2026-04-24 06:58:11.541838

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '32d16cea1275'
down_revision: Union[str, Sequence[str], None] = 'c504a40ccdd3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('articles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('analysis_report', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=True))

    with op.batch_alter_table('product_bases', schema=None) as batch_op:
        batch_op.add_column(sa.Column('analysis_report', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product_bases', schema=None) as batch_op:
        batch_op.drop_column('analysis_report')

    with op.batch_alter_table('articles', schema=None) as batch_op:
        batch_op.drop_column('analysis_report')

    # ### end Alembic commands ###
