"""add_chat_message_indexes

Revision ID: 386bdee21636
Revises: baa5e8e57d56
Create Date: 2026-05-03 07:42:55.824683

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '386bdee21636'
down_revision: Union[str, Sequence[str], None] = 'baa5e8e57d56'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chat_messages', schema=None) as batch_op:
        batch_op.create_index('ix_chat_deleted_at', ['deleted_at'], unique=False)
        batch_op.create_index('ix_chat_session_time', ['session_id', 'created_at'], unique=False)
        batch_op.create_index('ix_chat_user_time', ['user_id', 'created_at'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chat_messages', schema=None) as batch_op:
        batch_op.drop_index('ix_chat_user_time')
        batch_op.drop_index('ix_chat_session_time')
        batch_op.drop_index('ix_chat_deleted_at')

    # ### end Alembic commands ###
