"""add_revocation_support

Revision ID: 42777f61da1a
Revises: d15060915579
Create Date: 2026-04-05 10:01:53.199853

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '42777f61da1a'
down_revision: Union[str, Sequence[str], None] = 'd15060915579'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('support_knowledge_embeddings',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('knowledge_id', sa.String(), nullable=False),
    sa.Column('embedding', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('tenant_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['knowledge_id'], ['support_knowledge.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('support_knowledge_embeddings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_support_knowledge_embeddings_knowledge_id'), ['knowledge_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_support_knowledge_embeddings_tenant_id'), ['tenant_id'], unique=False)

    with op.batch_alter_table('support_chat_history', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_revoked', sa.Boolean(), server_default=sa.text('false'), nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('support_chat_history', schema=None) as batch_op:
        batch_op.drop_column('is_revoked')

    with op.batch_alter_table('support_knowledge_embeddings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_support_knowledge_embeddings_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_support_knowledge_embeddings_knowledge_id'))

    op.drop_table('support_knowledge_embeddings')
    # ### end Alembic commands ###
