"""add_campaign_events_table

Revision ID: 49ee5bd2de78
Revises: 74dd5186cd47
Create Date: 2026-03-09 21:54:11.099325

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '49ee5bd2de78'
down_revision: Union[str, Sequence[str], None] = '74dd5186cd47'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('campaign_events',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('campaign_id', sa.String(), nullable=False),
    sa.Column('event_type', sa.String(), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('tenant_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['campaign_id'], ['content_campaigns.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_campaign_events_campaign_id'), 'campaign_events', ['campaign_id'], unique=False)
    op.create_index(op.f('ix_campaign_events_event_type'), 'campaign_events', ['event_type'], unique=False)
    op.create_index('ix_campaign_events_tenant', 'campaign_events', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_campaign_events_tenant_id'), 'campaign_events', ['tenant_id'], unique=False)
    # [Elite V2.2 Fix] v567 đã được neutralize (pass) → indexes này có thể không tồn tại
    # khi upgrade từ DB trắng. Dùng IF EXISTS để an toàn.
    op.execute('DROP INDEX IF EXISTS ix_chat_messages_session_id_created_at_desc')
    op.execute('DROP INDEX IF EXISTS ix_chat_messages_user_id_created_at_desc')
    op.drop_index(op.f('ix_campaigns_user_id'), table_name='content_campaigns')
    op.drop_column('content_campaigns', 'error_logs')
    # ### end Alembic commands ###
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_campaign_events_tenant_id'), table_name='campaign_events')
    op.drop_index('ix_campaign_events_tenant', table_name='campaign_events')
    op.drop_index(op.f('ix_campaign_events_event_type'), table_name='campaign_events')
    op.drop_index(op.f('ix_campaign_events_campaign_id'), table_name='campaign_events')
    op.drop_table('campaign_events')
    # ### end Alembic commands ###
