"""add_market_price_intel_to_product

Revision ID: 52685c4e9fa1
Revises: f7f676cd2679
Create Date: 2026-04-27 07:13:35.724002

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '52685c4e9fa1'
down_revision: Union[str, Sequence[str], None] = 'f7f676cd2679'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product_bases', schema=None) as batch_op:
        batch_op.add_column(sa.Column('market_data', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=True))
        batch_op.add_column(sa.Column('last_market_sync', sa.DateTime(timezone=True), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product_bases', schema=None) as batch_op:
        batch_op.drop_column('last_market_sync')
        batch_op.drop_column('market_data')

    # ### end Alembic commands ###
