"""add_customer_location_to_reviews

Revision ID: 52d25e9d745d
Revises: 9be620891634
Create Date: 2026-03-31 14:36:29.850255

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '52d25e9d745d'
down_revision: Union[str, Sequence[str], None] = '9be620891634'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('system_reviews', schema=None) as batch_op:
        batch_op.add_column(sa.Column('customer_location', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('system_reviews', schema=None) as batch_op:
        batch_op.drop_column('customer_location')

    # ### end Alembic commands ###
