"""Add cancellation_reason and history to Order

Revision ID: 555c317a0043
Revises: eea58dee8ce0
Create Date: 2026-03-04 03:54:16.050309

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '555c317a0043'
down_revision: Union[str, Sequence[str], None] = 'eea58dee8ce0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_articles_created_at', 'articles', ['created_at'], unique=False)
    op.add_column('orders', sa.Column('cancellation_reason', sa.String(), nullable=True))
    op.add_column('orders', sa.Column('history', sa.JSON(), nullable=True))
    op.create_index('ix_orders_created_at', 'orders', ['created_at'], unique=False)
    op.create_index('ix_products_created_at', 'product_bases', ['created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_products_created_at', table_name='product_bases')
    op.drop_index('ix_orders_created_at', table_name='orders')
    op.drop_column('orders', 'history')
    op.drop_column('orders', 'cancellation_reason')
    op.drop_index('ix_articles_created_at', table_name='articles')
    # ### end Alembic commands ###
