"""add_click_fraud_events

Revision ID: 59becf94aa02
Revises: 2c5440432612
Create Date: 2026-05-11 20:35:25.401104

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '59becf94aa02'
down_revision: Union[str, Sequence[str], None] = '2c5440432612'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('click_fraud_events',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('gclid', sa.String(length=256), nullable=True),
    sa.Column('campaign_id', sa.String(length=64), nullable=True),
    sa.Column('ad_group_id', sa.String(length=64), nullable=True),
    sa.Column('keyword', sa.String(length=256), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=False),
    sa.Column('user_agent', sa.String(length=512), nullable=True),
    sa.Column('referrer', sa.String(length=512), nullable=True),
    sa.Column('landing_url', sa.String(length=512), nullable=True),
    sa.Column('ip_country', sa.String(length=8), nullable=True),
    sa.Column('ip_org', sa.String(length=128), nullable=True),
    sa.Column('is_datacenter', sa.Boolean(), nullable=False),
    sa.Column('is_vpn', sa.Boolean(), nullable=False),
    sa.Column('is_tor', sa.Boolean(), nullable=False),
    sa.Column('is_proxy', sa.Boolean(), nullable=False),
    sa.Column('session_duration_ms', sa.Integer(), nullable=False),
    sa.Column('scroll_depth_percent', sa.Float(), nullable=False),
    sa.Column('mouse_events_count', sa.Integer(), nullable=False),
    sa.Column('touch_events_count', sa.Integer(), nullable=False),
    sa.Column('webdriver_detected', sa.Boolean(), nullable=False),
    sa.Column('fraud_score', sa.Float(), nullable=False),
    sa.Column('verdict', sa.String(length=16), nullable=False),
    sa.Column('triggered_signals', sa.Text(), nullable=True),
    sa.Column('session_fingerprint', sa.String(length=32), nullable=True),
    sa.Column('reported_to_google', sa.Boolean(), nullable=False),
    sa.Column('investigation_batch_id', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('click_fraud_events', schema=None) as batch_op:
        batch_op.create_index('ix_cfe_gclid', ['gclid'], unique=False)
        batch_op.create_index('ix_cfe_ip_created', ['ip_address', 'created_at'], unique=False)
        batch_op.create_index('ix_cfe_verdict_created', ['verdict', 'created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_click_fraud_events_fraud_score'), ['fraud_score'], unique=False)
        batch_op.create_index(batch_op.f('ix_click_fraud_events_gclid'), ['gclid'], unique=False)
        batch_op.create_index(batch_op.f('ix_click_fraud_events_ip_address'), ['ip_address'], unique=False)
        batch_op.create_index(batch_op.f('ix_click_fraud_events_verdict'), ['verdict'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('click_fraud_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_click_fraud_events_verdict'))
        batch_op.drop_index(batch_op.f('ix_click_fraud_events_ip_address'))
        batch_op.drop_index(batch_op.f('ix_click_fraud_events_gclid'))
        batch_op.drop_index(batch_op.f('ix_click_fraud_events_fraud_score'))
        batch_op.drop_index('ix_cfe_verdict_created')
        batch_op.drop_index('ix_cfe_ip_created')
        batch_op.drop_index('ix_cfe_gclid')

    op.drop_table('click_fraud_events')
    # ### end Alembic commands ###
