"""Add Order Identity Snapshot fields v2

Revision ID: 5e4abb3a5c8a
Revises: 45b56de904de
Create Date: 2026-03-26 04:10:44.656844

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
"""Add Order Identity Snapshot fields v2

Revision ID: 5e4abb3a5c8a
Revises: 45b56de904de
Create Date: 2026-03-26 04:10:44.656844

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5e4abb3a5c8a'
down_revision: Union[str, Sequence[str], None] = '45b56de904de'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('customer_name', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('customer_phone', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('customer_address', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('customer_ip', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('order_metadata', sa.JSON(), nullable=True))
        batch_op.create_index(batch_op.f('ix_orders_customer_name'), ['customer_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_orders_customer_phone'), ['customer_phone'], unique=False)

    # Update existing rows
    op.execute("UPDATE orders SET order_metadata = '{}' WHERE order_metadata IS NULL")

    # Set to NOT NULL
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.alter_column('order_metadata', nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_orders_customer_phone'))
        batch_op.drop_index(batch_op.f('ix_orders_customer_name'))
        batch_op.drop_column('order_metadata')
        batch_op.drop_column('customer_ip')
        batch_op.drop_column('customer_address')
        batch_op.drop_column('customer_phone')
        batch_op.drop_column('customer_name')

    # ### end Alembic commands ###
