"""add_system_reviews_polymorphic

Revision ID: 6a5d7bd644b7
Revises: 7b595712a7f3
Create Date: 2026-03-31 14:08:25.281189

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6a5d7bd644b7'
down_revision: Union[str, Sequence[str], None] = '7b595712a7f3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('system_reviews',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('entity_type', sa.Enum('PRODUCT', 'NEWS', name='reviewentitytype'), nullable=False),
    sa.Column('entity_id', sa.String(), nullable=False),
    sa.Column('customer_name', sa.String(length=255), nullable=False),
    sa.Column('customer_phone', sa.String(length=20), nullable=True),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('tenant_id', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('system_reviews', schema=None) as batch_op:
        batch_op.create_index('ix_sys_reviews_created_at_status', ['created_at', 'status'], unique=False)
        batch_op.create_index('ix_sys_reviews_entity', ['entity_type', 'entity_id'], unique=False)
        batch_op.create_index('ix_sys_reviews_tenant_deleted', ['tenant_id', 'deleted_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_system_reviews_entity_id'), ['entity_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_system_reviews_entity_type'), ['entity_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_system_reviews_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_system_reviews_tenant_id'), ['tenant_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('system_reviews', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_system_reviews_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_system_reviews_status'))
        batch_op.drop_index(batch_op.f('ix_system_reviews_entity_type'))
        batch_op.drop_index(batch_op.f('ix_system_reviews_entity_id'))
        batch_op.drop_index('ix_sys_reviews_tenant_deleted')
        batch_op.drop_index('ix_sys_reviews_entity')
        batch_op.drop_index('ix_sys_reviews_created_at_status')

    op.drop_table('system_reviews')
    # ### end Alembic commands ###
