"""add_discount_price

Revision ID: 70e7b7bd1213
Revises: 5e4abb3a5c8a
Create Date: 2026-03-26 15:34:44.001044

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '70e7b7bd1213'
down_revision: Union[str, Sequence[str], None] = '5e4abb3a5c8a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product_bases', schema=None) as batch_op:
        batch_op.add_column(sa.Column('discount_price', sa.Float(), nullable=True))

    with op.batch_alter_table('product_variants', schema=None) as batch_op:
        batch_op.add_column(sa.Column('discount_price', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product_variants', schema=None) as batch_op:
        batch_op.drop_column('discount_price')

    with op.batch_alter_table('product_bases', schema=None) as batch_op:
        batch_op.drop_column('discount_price')

    # ### end Alembic commands ###
