"""add_category_v22_fields

Revision ID: 71037d3028b2
Revises: 4b790bc6dd9c
Create Date: 2026-04-16 14:41:12.789569

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '71037d3028b2'
down_revision: Union[str, Sequence[str], None] = '4b790bc6dd9c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.add_column(sa.Column('position', sa.Integer(), server_default='0', nullable=False))
        batch_op.add_column(sa.Column('show_on_mobile', sa.Boolean(), server_default='true', nullable=False))
        batch_op.add_column(sa.Column('show_on_desktop', sa.Boolean(), server_default='true', nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.drop_column('show_on_desktop')
        batch_op.drop_column('show_on_mobile')
        batch_op.drop_column('position')

    # ### end Alembic commands ###
