"""Add seo_keywords to Product

Revision ID: 74f09c37b688
Revises: e90554f97066
Create Date: 2026-03-23 06:14:02.427579

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '74f09c37b688'
down_revision: Union[str, Sequence[str], None] = 'e90554f97066'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product_bases', sa.Column('seo_keywords', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('product_bases', 'seo_keywords')
    # ### end Alembic commands ###
