"""Add ContentCampaign table

Revision ID: 7567818246e1
Revises: 99861331eefd
Create Date: 2026-03-07 13:07:51.299132

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7567818246e1'
down_revision: Union[str, Sequence[str], None] = '99861331eefd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('content_campaigns',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('source_input', sa.Text(), nullable=False),
    sa.Column('reviewer_type', sa.String(), nullable=False),
    sa.Column('current_step', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('gold_metadata', sa.JSON(), nullable=True),
    sa.Column('topic_data', sa.JSON(), nullable=True),
    sa.Column('assets_data', sa.JSON(), nullable=True),
    sa.Column('outline_data', sa.JSON(), nullable=True),
    sa.Column('draft_content', sa.Text(), nullable=True),
    sa.Column('unique_score', sa.Float(), nullable=False),
    sa.Column('final_html', sa.Text(), nullable=True),
    sa.Column('error_logs', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('tenant_id', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_campaigns_status', 'content_campaigns', ['status'], unique=False)
    op.create_index('ix_campaigns_tenant_deleted', 'content_campaigns', ['tenant_id', 'deleted_at'], unique=False)
    op.create_index(op.f('ix_content_campaigns_tenant_id'), 'content_campaigns', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_content_campaigns_tenant_id'), table_name='content_campaigns')
    op.drop_index('ix_campaigns_tenant_deleted', table_name='content_campaigns')
    op.drop_index('ix_campaigns_status', table_name='content_campaigns')
    op.drop_table('content_campaigns')
    # ### end Alembic commands ###
