"""Expand SupportKnowledge

Revision ID: 7a5bcc5b8068
Revises: fe0e6bbf45b5
Create Date: 2026-05-22 13:00:19.380417

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7a5bcc5b8068'
down_revision: Union[str, Sequence[str], None] = 'fe0e6bbf45b5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###


    with op.batch_alter_table('support_knowledge', schema=None) as batch_op:
        batch_op.add_column(sa.Column('product_id', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('source_type', sa.String(length=20), nullable=False))
        batch_op.add_column(sa.Column('source_url', sa.Text(), nullable=True))
        batch_op.create_index(batch_op.f('ix_support_knowledge_product_id'), ['product_id'], unique=False)
        batch_op.create_foreign_key(None, 'product_bases', ['product_id'], ['id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('support_knowledge', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_support_knowledge_product_id'))
        batch_op.drop_column('source_url')
        batch_op.drop_column('source_type')
        batch_op.drop_column('product_id')



    # ### end Alembic commands ###
