"""Add security_stamp

Revision ID: 7b595712a7f3
Revises: 7ebf2958f235
Create Date: 2026-03-31 12:43:03.214793

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7b595712a7f3'
down_revision: Union[str, Sequence[str], None] = '7ebf2958f235'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('security_stamp', sa.String(), nullable=False, server_default=sa.text('gen_random_uuid()::varchar')))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('security_stamp')

    # ### end Alembic commands ###
