"""add_ai_featured_to_product

Revision ID: 7d2c1763ceb5
Revises: ad70_add_category_icon
Create Date: 2026-04-10 14:09:49.011833

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7d2c1763ceb5'
down_revision: Union[str, Sequence[str], None] = 'ad70_add_category_icon'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product_bases', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_ai_featured', sa.Boolean(), nullable=False))
        batch_op.create_index(batch_op.f('ix_product_bases_is_ai_featured'), ['is_ai_featured'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product_bases', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_product_bases_is_ai_featured'))
        batch_op.drop_column('is_ai_featured')

    # ### end Alembic commands ###
