"""add product_metadata to product_bases

Revision ID: 7ebf2958f235
Revises: v569_add_short_desc
Create Date: 2026-03-29 06:55:31.756230

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7ebf2958f235'
down_revision: Union[str, Sequence[str], None] = 'v569_add_short_desc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    from sqlalchemy.dialects import postgresql
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product_bases', schema=None) as batch_op:
        batch_op.add_column(sa.Column('product_metadata', postgresql.JSONB(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product_bases', schema=None) as batch_op:
        batch_op.drop_column('product_metadata')

    # ### end Alembic commands ###
