"""Add customer identification to support chat history

Revision ID: 8563cdd22c16
Revises: 52d25e9d745d
Create Date: 2026-04-02 15:09:40.245698

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8563cdd22c16'
down_revision: Union[str, Sequence[str], None] = '52d25e9d745d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('support_chat_history', schema=None) as batch_op:
        batch_op.add_column(sa.Column('customer_name', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('customer_phone', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('support_chat_history', schema=None) as batch_op:
        batch_op.drop_column('customer_phone')
        batch_op.drop_column('customer_name')

    # ### end Alembic commands ###
