"""add_content_scout_table

Revision ID: 8989f4681a47
Revises: af61335218c6
Create Date: 2026-03-25 08:07:24.114784

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8989f4681a47'
down_revision: Union[str, Sequence[str], None] = 'af61335218c6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('content_scouts',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('topic', sa.String(), nullable=False),
    sa.Column('report_data', sa.JSON(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('tenant_id', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('content_scouts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_content_scouts_expires_at'), ['expires_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_content_scouts_tenant_id'), ['tenant_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_content_scouts_topic'), ['topic'], unique=False)
        batch_op.create_index('ix_scouts_tenant_topic', ['tenant_id', 'topic'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('content_scouts', schema=None) as batch_op:
        batch_op.drop_index('ix_scouts_tenant_topic')
        batch_op.drop_index(batch_op.f('ix_content_scouts_topic'))
        batch_op.drop_index(batch_op.f('ix_content_scouts_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_content_scouts_expires_at'))

    op.drop_table('content_scouts')
    # ### end Alembic commands ###
