"""add_neural_audit_scores_v26

Revision ID: 972ea4561203
Revises: 19c1873b85a8
Create Date: 2026-05-12 11:30:07.920461

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '972ea4561203'
down_revision: Union[str, Sequence[str], None] = '19c1873b85a8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('google_ads_campaign_logs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('seo_score', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('sge_score', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('quality_score', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('google_ads_campaign_logs', schema=None) as batch_op:
        batch_op.drop_column('quality_score')
        batch_op.drop_column('sge_score')
        batch_op.drop_column('seo_score')

    # ### end Alembic commands ###
