"""verify_gold_metadata_and_unique_score

Revision ID: 994c68ed3a6c
Revises: b2c62adc5cc4
Create Date: 2026-03-12 07:31:44.757078

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '994c68ed3a6c'
down_revision: Union[str, Sequence[str], None] = 'b2c62adc5cc4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('article_embeddings', 'embedding',
               existing_type=sa.NullType(),
               nullable=False)
    op.drop_index(op.f('ix_article_embeddings_ivfflat'), table_name='article_embeddings', postgresql_ops={'embedding': 'vector_cosine_ops'}, postgresql_with={'lists': '10'}, postgresql_using='ivfflat')
    op.drop_column('article_embeddings', 'content_hash')
    op.alter_column('product_embeddings', 'embedding',
               existing_type=sa.NullType(),
               nullable=False)
    op.drop_index(op.f('ix_product_embeddings_ivfflat'), table_name='product_embeddings', postgresql_ops={'embedding': 'vector_cosine_ops'}, postgresql_with={'lists': '10'}, postgresql_using='ivfflat')
    op.drop_column('product_embeddings', 'content_hash')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product_embeddings', sa.Column('content_hash', sa.VARCHAR(length=64), autoincrement=False, nullable=True))
    op.create_index(op.f('ix_product_embeddings_ivfflat'), 'product_embeddings', ['embedding'], unique=False, postgresql_ops={'embedding': 'vector_cosine_ops'}, postgresql_with={'lists': '10'}, postgresql_using='ivfflat')
    op.alter_column('product_embeddings', 'embedding',
               existing_type=sa.NullType(),
               nullable=True)
    op.add_column('article_embeddings', sa.Column('content_hash', sa.VARCHAR(length=64), autoincrement=False, nullable=True))
    op.create_index(op.f('ix_article_embeddings_ivfflat'), 'article_embeddings', ['embedding'], unique=False, postgresql_ops={'embedding': 'vector_cosine_ops'}, postgresql_with={'lists': '10'}, postgresql_using='ivfflat')
    op.alter_column('article_embeddings', 'embedding',
               existing_type=sa.NullType(),
               nullable=True)
    # ### end Alembic commands ###
