"""add_chat_settings_to_voice_profile

Revision ID: 99861331eefd
Revises: v567_add_chat_indexes
Create Date: 2026-03-07 02:56:25.908705

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '99861331eefd'
down_revision: Union[str, Sequence[str], None] = 'v567_add_chat_indexes'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('voice_profiles', sa.Column('chat_settings', sa.JSON(), nullable=False, server_default='{}'))
    op.alter_column('voice_profiles', 'farewell_template',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('voice_profiles', 'farewell_template',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('voice_profiles', 'chat_settings')
    # ### end Alembic commands ###
