"""add_unified_agent_task_table

Revision ID: 9a1bad71b605
Revises: v600_neural_media_linker
Create Date: 2026-04-04 11:06:46.756301

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9a1bad71b605'
down_revision: Union[str, Sequence[str], None] = 'v600_neural_media_linker'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('unified_agent_tasks',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('agent_id', sa.String(), nullable=False),
    sa.Column('task_id', sa.String(), nullable=False),
    sa.Column('session_id', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('result', sa.JSON(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('tenant_id', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('unified_agent_tasks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_unified_agent_tasks_agent_id'), ['agent_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_unified_agent_tasks_session_id'), ['session_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_unified_agent_tasks_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_unified_agent_tasks_task_id'), ['task_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_unified_agent_tasks_tenant_id'), ['tenant_id'], unique=False)
        batch_op.create_index('ix_unified_task_agent_status', ['agent_id', 'status'], unique=False)
        batch_op.create_index('ix_unified_task_tenant_status', ['tenant_id', 'status'], unique=False)

    with op.batch_alter_table('media_registry', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_media_linked_post'))
        batch_op.drop_index(batch_op.f('ix_media_registry_linked_post_id'))
        batch_op.drop_index(batch_op.f('ix_media_registry_linked_post_type'))
        batch_op.create_index(batch_op.f('ix_media_registry_is_linked'), ['is_linked'], unique=False)
        batch_op.drop_column('linked_post_id')
        batch_op.drop_column('linked_post_type')

    with op.batch_alter_table('media_usage', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_media_usage_tenant'))
        batch_op.create_index(batch_op.f('ix_media_usage_asset_id'), ['asset_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_media_usage_entity_id'), ['entity_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_media_usage_entity_type'), ['entity_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_media_usage_tenant_id'), ['tenant_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('media_usage', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_media_usage_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_media_usage_entity_type'))
        batch_op.drop_index(batch_op.f('ix_media_usage_entity_id'))
        batch_op.drop_index(batch_op.f('ix_media_usage_asset_id'))
        batch_op.create_index(batch_op.f('ix_media_usage_tenant'), ['tenant_id'], unique=False)

    with op.batch_alter_table('media_registry', schema=None) as batch_op:
        batch_op.add_column(sa.Column('linked_post_type', sa.VARCHAR(length=30), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('linked_post_id', sa.VARCHAR(), autoincrement=False, nullable=True))
        batch_op.drop_index(batch_op.f('ix_media_registry_is_linked'))
        batch_op.create_index(batch_op.f('ix_media_registry_linked_post_type'), ['linked_post_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_media_registry_linked_post_id'), ['linked_post_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_media_linked_post'), ['linked_post_type', 'linked_post_id'], unique=False)

    with op.batch_alter_table('unified_agent_tasks', schema=None) as batch_op:
        batch_op.drop_index('ix_unified_task_tenant_status')
        batch_op.drop_index('ix_unified_task_agent_status')
        batch_op.drop_index(batch_op.f('ix_unified_agent_tasks_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_unified_agent_tasks_task_id'))
        batch_op.drop_index(batch_op.f('ix_unified_agent_tasks_status'))
        batch_op.drop_index(batch_op.f('ix_unified_agent_tasks_session_id'))
        batch_op.drop_index(batch_op.f('ix_unified_agent_tasks_agent_id'))

    op.drop_table('unified_agent_tasks')
    # ### end Alembic commands ###
