"""Add tier_variations and tier_index for product

Revision ID: 9e2b36c9e700
Revises: 74f09c37b688
Create Date: 2026-03-23 06:56:06.201607

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9e2b36c9e700'
down_revision: Union[str, Sequence[str], None] = '74f09c37b688'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product_bases', sa.Column('tier_variations', sa.JSON(), nullable=True))
    op.add_column('product_variants', sa.Column('tier_index', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('product_variants', 'tier_index')
    op.drop_column('product_bases', 'tier_variations')
    # ### end Alembic commands ###
