"""add_ads_campaign_logs

Revision ID: 9e67322e3952
Revises: 59becf94aa02
Create Date: 2026-05-11 21:39:29.567132

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9e67322e3952'
down_revision: Union[str, Sequence[str], None] = '59becf94aa02'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('google_ads_campaign_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('campaign_id', sa.String(length=64), nullable=False),
    sa.Column('campaign_name', sa.String(length=256), nullable=False),
    sa.Column('action', sa.String(length=32), nullable=False),
    sa.Column('status_before', sa.String(length=32), nullable=True),
    sa.Column('status_after', sa.String(length=32), nullable=True),
    sa.Column('budget_before_vnd', sa.Float(), nullable=True),
    sa.Column('budget_after_vnd', sa.Float(), nullable=True),
    sa.Column('actor_id', sa.Integer(), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('policy_score', sa.Float(), nullable=True),
    sa.Column('is_compliant', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('google_ads_campaign_logs', schema=None) as batch_op:
        batch_op.create_index('ix_gacl_campaign_created', ['campaign_id', 'created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_google_ads_campaign_logs_campaign_id'), ['campaign_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('google_ads_campaign_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_google_ads_campaign_logs_campaign_id'))
        batch_op.drop_index('ix_gacl_campaign_created')

    op.drop_table('google_ads_campaign_logs')
    # ### end Alembic commands ###
