"""Add category to ContentCampaign

Revision ID: 9f4bd635a9b4
Revises: a3d29ac21439
Create Date: 2026-03-15 15:59:58.477783

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9f4bd635a9b4'
down_revision: Union[str, Sequence[str], None] = 'a3d29ac21439'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('content_campaigns', sa.Column('category', sa.String(), nullable=False, server_default='CREATIVE_CONTENT'))
    op.create_index(op.f('ix_content_campaigns_category'), 'content_campaigns', ['category'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_content_campaigns_category'), table_name='content_campaigns')
    op.drop_column('content_campaigns', 'category')
    # ### end Alembic commands ###
