"""Add model management fields to VoiceProfile final

Revision ID: a3d29ac21439
Revises: 20b368eb59d0
Create Date: 2026-03-13 16:14:36.002288

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a3d29ac21439'
down_revision: Union[str, Sequence[str], None] = '20b368eb59d0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('voice_profiles', sa.Column('ai_models', sa.JSON(), nullable=False))
    op.add_column('voice_profiles', sa.Column('primary_model', sa.String(), nullable=True))
    op.add_column('voice_profiles', sa.Column('discovered_models', sa.JSON(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('voice_profiles', 'discovered_models')
    op.drop_column('voice_profiles', 'primary_model')
    op.drop_column('voice_profiles', 'ai_models')
    # ### end Alembic commands ###
