"""Update SupportKnowledge Category to Enum

Revision ID: a97ea7e6a7ff
Revises: ed244f9f3d90
Create Date: 2026-04-02 16:04:35.908355

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a97ea7e6a7ff'
down_revision: Union[str, Sequence[str], None] = 'ed244f9f3d90'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
