"""auto_uuid_v7_defaults

Revision ID: ac3afa60b038
Revises: v606
Create Date: 2026-05-29 11:38:13.819942

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ac3afa60b038'
down_revision: Union[str, Sequence[str], None] = 'v606'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Self-healing migrations: Drop indexes and constraints safely using raw SQL
    op.execute("ALTER TABLE affiliate_profiles DROP CONSTRAINT IF EXISTS affiliate_profiles_ctv_code_key")
    op.execute("ALTER TABLE affiliate_profiles DROP CONSTRAINT IF EXISTS affiliate_profiles_user_id_key")
    op.execute("DROP INDEX IF EXISTS ix_affiliate_profiles_ctv_code")
    op.execute("DROP INDEX IF EXISTS ix_affiliate_profiles_status")
    op.execute("DROP INDEX IF EXISTS ix_affiliate_profiles_user_id")
    op.execute("ALTER TABLE affiliate_profiles DROP CONSTRAINT IF EXISTS affiliate_profiles_commission_tier_id_fkey")
    op.execute("ALTER TABLE affiliate_profiles DROP CONSTRAINT IF EXISTS affiliate_profiles_referred_by_ctv_id_fkey")

    with op.batch_alter_table('affiliate_profiles', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_affiliate_profiles_ctv_code'), ['ctv_code'], unique=True)
        batch_op.create_index(batch_op.f('ix_affiliate_profiles_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_affiliate_profiles_user_id'), ['user_id'], unique=True)
        batch_op.create_foreign_key(None, 'commission_tiers', ['commission_tier_id'], ['id'])
        batch_op.create_foreign_key(None, 'affiliate_profiles', ['referred_by_ctv_id'], ['id'])

    op.execute("ALTER TABLE commission_ledger DROP CONSTRAINT IF EXISTS commission_ledger_order_id_key")
    op.execute("DROP INDEX IF EXISTS ix_commission_ledger_order_id")
    op.execute("ALTER TABLE commission_ledger DROP CONSTRAINT IF EXISTS commission_ledger_affiliate_id_fkey")
    op.execute("ALTER TABLE commission_ledger DROP CONSTRAINT IF EXISTS commission_ledger_order_id_fkey")

    with op.batch_alter_table('commission_ledger', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_commission_ledger_order_id'), ['order_id'], unique=True)
        batch_op.create_foreign_key(None, 'orders', ['order_id'], ['id'])
        batch_op.create_foreign_key(None, 'affiliate_profiles', ['affiliate_id'], ['id'])

    op.execute("ALTER TABLE withdrawal_requests DROP CONSTRAINT IF EXISTS withdrawal_requests_admin_id_fkey")
    op.execute("ALTER TABLE withdrawal_requests DROP CONSTRAINT IF EXISTS withdrawal_requests_affiliate_id_fkey")

    with op.batch_alter_table('withdrawal_requests', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'affiliate_profiles', ['affiliate_id'], ['id'])
        batch_op.create_foreign_key(None, 'users', ['admin_id'], ['id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('withdrawal_requests', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('withdrawal_requests_affiliate_id_fkey'), 'affiliate_profiles', ['affiliate_id'], ['id'], ondelete='RESTRICT')
        batch_op.create_foreign_key(batch_op.f('withdrawal_requests_admin_id_fkey'), 'users', ['admin_id'], ['id'], ondelete='SET NULL')

    with op.batch_alter_table('commission_ledger', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('commission_ledger_order_id_fkey'), 'orders', ['order_id'], ['id'], ondelete='RESTRICT')
        batch_op.create_foreign_key(batch_op.f('commission_ledger_affiliate_id_fkey'), 'affiliate_profiles', ['affiliate_id'], ['id'], ondelete='RESTRICT')
        batch_op.drop_index(batch_op.f('ix_commission_ledger_order_id'))
        batch_op.create_index(batch_op.f('ix_commission_ledger_order_id'), ['order_id'], unique=False)
        batch_op.create_unique_constraint(batch_op.f('commission_ledger_order_id_key'), ['order_id'], postgresql_nulls_not_distinct=False)

    with op.batch_alter_table('affiliate_profiles', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('affiliate_profiles_referred_by_ctv_id_fkey'), 'affiliate_profiles', ['referred_by_ctv_id'], ['id'], ondelete='SET NULL')
        batch_op.create_foreign_key(batch_op.f('affiliate_profiles_commission_tier_id_fkey'), 'commission_tiers', ['commission_tier_id'], ['id'], ondelete='SET NULL')
        batch_op.drop_index(batch_op.f('ix_affiliate_profiles_user_id'))
        batch_op.create_index(batch_op.f('ix_affiliate_profiles_user_id'), ['user_id'], unique=False)
        batch_op.drop_index(batch_op.f('ix_affiliate_profiles_status'))
        batch_op.create_index(batch_op.f('ix_affiliate_profiles_status'), ['status', 'tenant_id'], unique=False)
        batch_op.drop_index(batch_op.f('ix_affiliate_profiles_ctv_code'))
        batch_op.create_index(batch_op.f('ix_affiliate_profiles_ctv_code'), ['ctv_code'], unique=False)
        batch_op.create_unique_constraint(batch_op.f('affiliate_profiles_user_id_key'), ['user_id'], postgresql_nulls_not_distinct=False)
        batch_op.create_unique_constraint(batch_op.f('affiliate_profiles_ctv_code_key'), ['ctv_code'], postgresql_nulls_not_distinct=False)

    # ### end Alembic commands ###
