"""add_recurring_fields

Revision ID: af61335218c6
Revises: b5adec8d04d6
Create Date: 2026-03-25 06:49:46.005813

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'af61335218c6'
down_revision: Union[str, Sequence[str], None] = 'b5adec8d04d6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('appointments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('recurring_type', sa.String(), nullable=False))
        batch_op.add_column(sa.Column('recurring_metadata', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('appointments', schema=None) as batch_op:
        batch_op.drop_column('recurring_metadata')
        batch_op.drop_column('recurring_type')

    # ### end Alembic commands ###
