"""Epic Task V62.2: Add stt_anchors and mic_sensitivity to VoiceProfile

Revision ID: b2c62adc5cc4
Revises: 49ee5bd2de78
Create Date: 2026-03-10 15:19:21.868042

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b2c62adc5cc4'
down_revision: Union[str, Sequence[str], None] = '49ee5bd2de78'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('voice_profiles', sa.Column('stt_anchors', sa.JSON(), nullable=False))
    op.add_column('voice_profiles', sa.Column('mic_sensitivity', sa.Float(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('voice_profiles', 'mic_sensitivity')
    op.drop_column('voice_profiles', 'stt_anchors')
    # ### end Alembic commands ###
