"""add_appointments_table

Revision ID: b5adec8d04d6
Revises: banner_v1
Create Date: 2026-03-25 06:32:29.960242

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b5adec8d04d6'
down_revision: Union[str, Sequence[str], None] = 'banner_v1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('appointments',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('start_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('campaign_id', sa.String(), nullable=True),
    sa.Column('metadata_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('tenant_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['campaign_id'], ['content_campaigns.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('appointments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_appointments_campaign_id'), ['campaign_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_appointments_start_time'), ['start_time'], unique=False)
        batch_op.create_index('ix_appointments_tenant_deleted', ['tenant_id', 'deleted_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_appointments_tenant_id'), ['tenant_id'], unique=False)
        batch_op.create_index('ix_appointments_time_range', ['start_time', 'end_time'], unique=False)

    with op.batch_alter_table('banners', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               nullable=False)
        batch_op.alter_column('updated_at',
               nullable=False)
        batch_op.alter_column('tenant_id',
               nullable=False)
        batch_op.drop_index(batch_op.f('ix_banners_tenant_deleted'))
        batch_op.create_index(batch_op.f('ix_banners_tenant_id'), ['tenant_id'], unique=False)

    with op.batch_alter_table('content_campaigns', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_content_campaigns_category'), ['category'], unique=False)

    with op.batch_alter_table('system_settings', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               nullable=False)
        batch_op.alter_column('updated_at',
               nullable=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('system_settings', schema=None) as batch_op:
        batch_op.alter_column('updated_at',
               nullable=True)
        batch_op.alter_column('created_at',
               nullable=True)

    with op.batch_alter_table('content_campaigns', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_content_campaigns_category'))

    with op.batch_alter_table('banners', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_banners_tenant_id'))
        batch_op.create_index(batch_op.f('ix_banners_tenant_deleted'), ['tenant_id', 'deleted_at'], unique=False)
        batch_op.alter_column('tenant_id',
               nullable=True)
        batch_op.alter_column('updated_at',
               nullable=True)
        batch_op.alter_column('created_at',
               nullable=True)

    with op.batch_alter_table('appointments', schema=None) as batch_op:
        batch_op.drop_index('ix_appointments_time_range')
        batch_op.drop_index(batch_op.f('ix_appointments_tenant_id'))
        batch_op.drop_index('ix_appointments_tenant_deleted')
        batch_op.drop_index(batch_op.f('ix_appointments_start_time'))
        batch_op.drop_index(batch_op.f('ix_appointments_campaign_id'))

    op.drop_table('appointments')
    # ### end Alembic commands ###
