"""add rich review fields

Revision ID: b7c8d9e1f2a3
Revises: 52d25e9d745d
Create Date: 2026-04-12 13:58:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b7c8d9e1f2a3'
down_revision: Union[str, None] = '29ceb4ebe528' # Corrected parent
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('system_reviews', sa.Column('attributes', sa.JSON(), nullable=True))
    op.add_column('system_reviews', sa.Column('attachments', sa.JSON(), nullable=True))
    op.add_column('system_reviews', sa.Column('likes_count', sa.Integer(), nullable=False, server_default='0'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('system_reviews', 'likes_count')
    op.drop_column('system_reviews', 'attachments')
    op.drop_column('system_reviews', 'attributes')
    # ### end Alembic commands ###
