"""add_seo_pillar_cluster_tables

Revision ID: b9a7eec0272c
Revises: df731fe3f96e
Create Date: 2026-06-12 07:01:28.494480

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b9a7eec0272c'
down_revision: Union[str, Sequence[str], None] = 'df731fe3f96e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('seo_nodes',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('entity_type', sa.Enum('ARTICLE', 'PRODUCT', name='seo_entity_type_enum'), nullable=False),
    sa.Column('entity_id', sa.String(), nullable=False),
    sa.Column('is_pillar', sa.Boolean(), nullable=False),
    sa.Column('pillar_topic', sa.String(length=255), nullable=True),
    sa.Column('node_label', sa.String(length=500), nullable=False),
    sa.Column('node_slug', sa.String(length=500), nullable=False),
    sa.Column('node_url', sa.String(length=1000), nullable=True),
    sa.Column('ai_summary', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('tenant_id', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('entity_type', 'entity_id', 'tenant_id', name='uq_seo_node_entity_tenant')
    )
    with op.batch_alter_table('seo_nodes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_seo_nodes_entity_id'), ['entity_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_seo_nodes_entity_type'), ['entity_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_seo_nodes_is_pillar'), ['is_pillar'], unique=False)
        batch_op.create_index('ix_seo_nodes_pillar', ['is_pillar', 'tenant_id'], unique=False)
        batch_op.create_index('ix_seo_nodes_tenant_deleted', ['tenant_id', 'deleted_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_seo_nodes_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('seo_edges',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('source_node_id', sa.String(), nullable=False),
    sa.Column('target_node_id', sa.String(), nullable=False),
    sa.Column('link_type', sa.Enum('PILLAR_CLUSTER', 'RELATED', 'MANUAL', 'AI_SUGGESTED', name='seo_link_type_enum'), nullable=False),
    sa.Column('ai_confidence', sa.Float(), nullable=True),
    sa.Column('ai_reasoning', sa.Text(), nullable=True),
    sa.Column('is_confirmed', sa.Boolean(), nullable=False),
    sa.Column('override_by', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('tenant_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['source_node_id'], ['seo_nodes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['target_node_id'], ['seo_nodes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_node_id', 'target_node_id', 'tenant_id', name='uq_seo_edge_source_target')
    )
    with op.batch_alter_table('seo_edges', schema=None) as batch_op:
        batch_op.create_index('ix_seo_edges_confirmed', ['is_confirmed', 'tenant_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_seo_edges_is_confirmed'), ['is_confirmed'], unique=False)
        batch_op.create_index(batch_op.f('ix_seo_edges_link_type'), ['link_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_seo_edges_source_node_id'), ['source_node_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_seo_edges_target_node_id'), ['target_node_id'], unique=False)
        batch_op.create_index('ix_seo_edges_tenant', ['tenant_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_seo_edges_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('seo_pillar_embeddings',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('node_id', sa.String(), nullable=False),
    sa.Column('embedding', sa.Text(), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=True),
    sa.Column('model_name', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['node_id'], ['seo_nodes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('node_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('seo_pillar_embeddings')
    with op.batch_alter_table('seo_edges', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_seo_edges_tenant_id'))
        batch_op.drop_index('ix_seo_edges_tenant')
        batch_op.drop_index(batch_op.f('ix_seo_edges_target_node_id'))
        batch_op.drop_index(batch_op.f('ix_seo_edges_source_node_id'))
        batch_op.drop_index(batch_op.f('ix_seo_edges_link_type'))
        batch_op.drop_index(batch_op.f('ix_seo_edges_is_confirmed'))
        batch_op.drop_index('ix_seo_edges_confirmed')

    op.drop_table('seo_edges')
    with op.batch_alter_table('seo_nodes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_seo_nodes_tenant_id'))
        batch_op.drop_index('ix_seo_nodes_tenant_deleted')
        batch_op.drop_index('ix_seo_nodes_pillar')
        batch_op.drop_index(batch_op.f('ix_seo_nodes_is_pillar'))
        batch_op.drop_index(batch_op.f('ix_seo_nodes_entity_type'))
        batch_op.drop_index(batch_op.f('ix_seo_nodes_entity_id'))

    op.drop_table('seo_nodes')
    # ### end Alembic commands ###
