"""Add loyalty security fields

Revision ID: ba5acbaada22
Revises: v602_add_loyalty_system
Create Date: 2026-04-20 09:16:22.220596

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ba5acbaada22'
down_revision: Union[str, Sequence[str], None] = 'v602_add_loyalty_system'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('point_transactions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('integrity_token', sa.String(), nullable=True))
        batch_op.alter_column('created_at',
               nullable=False,
               existing_server_default=sa.text('now()'))
        batch_op.alter_column('updated_at',
               nullable=False,
               existing_server_default=sa.text('now()'))
        batch_op.create_index(batch_op.f('ix_point_transactions_order_id'), ['order_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_point_transactions_user_id'), ['user_id'], unique=False)
        batch_op.drop_constraint(batch_op.f('point_transactions_order_id_fkey'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('point_transactions_user_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'])
        batch_op.create_foreign_key(None, 'orders', ['order_id'], ['id'])

    with op.batch_alter_table('user_loyalty', schema=None) as batch_op:
        batch_op.add_column(sa.Column('balance_seal', sa.String(), nullable=True))
        batch_op.alter_column('user_id',
               nullable=False)
        batch_op.alter_column('created_at',
               nullable=False,
               existing_server_default=sa.text('now()'))
        batch_op.alter_column('updated_at',
               nullable=False,
               existing_server_default=sa.text('now()'))
        batch_op.drop_constraint(batch_op.f('user_loyalty_user_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_loyalty', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('user_loyalty_user_id_fkey'), 'users', ['user_id'], ['id'], ondelete='CASCADE')
        batch_op.alter_column('updated_at',
               nullable=True,
               existing_server_default=sa.text('now()'))
        batch_op.alter_column('created_at',
               nullable=True,
               existing_server_default=sa.text('now()'))
        batch_op.alter_column('user_id',
               nullable=True)
        batch_op.drop_column('balance_seal')

    with op.batch_alter_table('point_transactions', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('point_transactions_user_id_fkey'), 'users', ['user_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(batch_op.f('point_transactions_order_id_fkey'), 'orders', ['order_id'], ['id'], ondelete='SET NULL')
        batch_op.drop_index(batch_op.f('ix_point_transactions_user_id'))
        batch_op.drop_index(batch_op.f('ix_point_transactions_order_id'))
        batch_op.alter_column('updated_at',
               nullable=True,
               existing_server_default=sa.text('now()'))
        batch_op.alter_column('created_at',
               nullable=True,
               existing_server_default=sa.text('now()'))
        batch_op.drop_column('integrity_token')

    # ### end Alembic commands ###
