"""add_performance_indexes

Revision ID: c188ef9140f1
Revises: v605
Create Date: 2026-05-28 19:56:47.592458

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c188ef9140f1'
down_revision: Union[str, Sequence[str], None] = 'v605'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('affiliate_profiles', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               nullable=False,
               existing_server_default=sa.text('now()'))
        batch_op.alter_column('updated_at',
               nullable=False,
               existing_server_default=sa.text('now()'))
        batch_op.drop_constraint(batch_op.f('affiliate_profiles_ctv_code_key'), type_='unique')
        batch_op.drop_constraint(batch_op.f('affiliate_profiles_user_id_key'), type_='unique')
        batch_op.drop_index(batch_op.f('ix_affiliate_profiles_ctv_code'))
        batch_op.create_index(batch_op.f('ix_affiliate_profiles_ctv_code'), ['ctv_code'], unique=True)
        batch_op.drop_index(batch_op.f('ix_affiliate_profiles_user_id'))
        batch_op.create_index(batch_op.f('ix_affiliate_profiles_user_id'), ['user_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_affiliate_profiles_tenant_id'), ['tenant_id'], unique=False)
        batch_op.drop_constraint(batch_op.f('affiliate_profiles_commission_tier_id_fkey'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('affiliate_profiles_referred_by_ctv_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'affiliate_profiles', ['referred_by_ctv_id'], ['id'])
        batch_op.create_foreign_key(None, 'commission_tiers', ['commission_tier_id'], ['id'])

    with op.batch_alter_table('articles', schema=None) as batch_op:
        batch_op.create_index('ix_articles_deleted_at', ['deleted_at'], unique=False)
        batch_op.create_index('ix_articles_status', ['status'], unique=False)

    with op.batch_alter_table('commission_ledger', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               nullable=False,
               existing_server_default=sa.text('now()'))
        batch_op.alter_column('updated_at',
               nullable=False,
               existing_server_default=sa.text('now()'))
        batch_op.drop_constraint(batch_op.f('commission_ledger_order_id_key'), type_='unique')
        batch_op.drop_index(batch_op.f('ix_commission_ledger_order_id'))
        batch_op.create_index(batch_op.f('ix_commission_ledger_order_id'), ['order_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_commission_ledger_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_commission_ledger_tenant_id'), ['tenant_id'], unique=False)
        batch_op.drop_constraint(batch_op.f('commission_ledger_order_id_fkey'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('commission_ledger_affiliate_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'orders', ['order_id'], ['id'])
        batch_op.create_foreign_key(None, 'affiliate_profiles', ['affiliate_id'], ['id'])

    with op.batch_alter_table('commission_tiers', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               nullable=False,
               existing_server_default=sa.text('now()'))
        batch_op.alter_column('updated_at',
               nullable=False,
               existing_server_default=sa.text('now()'))
        batch_op.create_index(batch_op.f('ix_commission_tiers_tenant_id'), ['tenant_id'], unique=False)

    with op.batch_alter_table('product_bases', schema=None) as batch_op:
        batch_op.alter_column('ctv_rate_override',
               comment=None,
               existing_comment='Phase 2 Hybrid CTV: NULL=tier rate, 0.0=no commission, 0.2=force 20%',
               existing_nullable=True)
        batch_op.create_index('ix_products_category_id', ['category_id'], unique=False)
        batch_op.create_index('ix_products_deleted_at', ['deleted_at'], unique=False)
        batch_op.create_index('ix_products_status_deleted', ['status', 'deleted_at'], unique=False)

    with op.batch_alter_table('product_variants', schema=None) as batch_op:
        batch_op.create_index('ix_product_variants_deleted_at', ['deleted_at'], unique=False)
        batch_op.create_index('ix_product_variants_product_base_id', ['product_base_id'], unique=False)

    with op.batch_alter_table('vouchers', schema=None) as batch_op:
        batch_op.create_index('ix_vouchers_active_viral', ['is_active', 'is_viral'], unique=False)
        batch_op.create_index('ix_vouchers_deleted_at', ['deleted_at'], unique=False)
        batch_op.create_index('ix_vouchers_tenant_deleted', ['tenant_id', 'deleted_at'], unique=False)

    with op.batch_alter_table('withdrawal_requests', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               nullable=False,
               existing_server_default=sa.text('now()'))
        batch_op.alter_column('updated_at',
               nullable=False,
               existing_server_default=sa.text('now()'))
        batch_op.create_index(batch_op.f('ix_withdrawal_requests_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_withdrawal_requests_tenant_id'), ['tenant_id'], unique=False)
        batch_op.drop_constraint(batch_op.f('withdrawal_requests_admin_id_fkey'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('withdrawal_requests_affiliate_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'affiliate_profiles', ['affiliate_id'], ['id'])
        batch_op.create_foreign_key(None, 'users', ['admin_id'], ['id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('withdrawal_requests', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('withdrawal_requests_affiliate_id_fkey'), 'affiliate_profiles', ['affiliate_id'], ['id'], ondelete='RESTRICT')
        batch_op.create_foreign_key(batch_op.f('withdrawal_requests_admin_id_fkey'), 'users', ['admin_id'], ['id'], ondelete='SET NULL')
        batch_op.drop_index(batch_op.f('ix_withdrawal_requests_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_withdrawal_requests_status'))
        batch_op.alter_column('updated_at',
               nullable=True,
               existing_server_default=sa.text('now()'))
        batch_op.alter_column('created_at',
               nullable=True,
               existing_server_default=sa.text('now()'))

    with op.batch_alter_table('vouchers', schema=None) as batch_op:
        batch_op.drop_index('ix_vouchers_tenant_deleted')
        batch_op.drop_index('ix_vouchers_deleted_at')
        batch_op.drop_index('ix_vouchers_active_viral')

    with op.batch_alter_table('product_variants', schema=None) as batch_op:
        batch_op.drop_index('ix_product_variants_product_base_id')
        batch_op.drop_index('ix_product_variants_deleted_at')

    with op.batch_alter_table('product_bases', schema=None) as batch_op:
        batch_op.drop_index('ix_products_status_deleted')
        batch_op.drop_index('ix_products_deleted_at')
        batch_op.drop_index('ix_products_category_id')
        batch_op.alter_column('ctv_rate_override',
               comment='Phase 2 Hybrid CTV: NULL=tier rate, 0.0=no commission, 0.2=force 20%',
               existing_nullable=True)

    with op.batch_alter_table('commission_tiers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_commission_tiers_tenant_id'))
        batch_op.alter_column('updated_at',
               nullable=True,
               existing_server_default=sa.text('now()'))
        batch_op.alter_column('created_at',
               nullable=True,
               existing_server_default=sa.text('now()'))

    with op.batch_alter_table('commission_ledger', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('commission_ledger_affiliate_id_fkey'), 'affiliate_profiles', ['affiliate_id'], ['id'], ondelete='RESTRICT')
        batch_op.create_foreign_key(batch_op.f('commission_ledger_order_id_fkey'), 'orders', ['order_id'], ['id'], ondelete='RESTRICT')
        batch_op.drop_index(batch_op.f('ix_commission_ledger_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_commission_ledger_status'))
        batch_op.drop_index(batch_op.f('ix_commission_ledger_order_id'))
        batch_op.create_index(batch_op.f('ix_commission_ledger_order_id'), ['order_id'], unique=False)
        batch_op.create_unique_constraint(batch_op.f('commission_ledger_order_id_key'), ['order_id'], postgresql_nulls_not_distinct=False)
        batch_op.alter_column('updated_at',
               nullable=True,
               existing_server_default=sa.text('now()'))
        batch_op.alter_column('created_at',
               nullable=True,
               existing_server_default=sa.text('now()'))

    with op.batch_alter_table('articles', schema=None) as batch_op:
        batch_op.drop_index('ix_articles_status')
        batch_op.drop_index('ix_articles_deleted_at')

    with op.batch_alter_table('affiliate_profiles', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('affiliate_profiles_referred_by_ctv_id_fkey'), 'affiliate_profiles', ['referred_by_ctv_id'], ['id'], ondelete='SET NULL')
        batch_op.create_foreign_key(batch_op.f('affiliate_profiles_commission_tier_id_fkey'), 'commission_tiers', ['commission_tier_id'], ['id'], ondelete='SET NULL')
        batch_op.drop_index(batch_op.f('ix_affiliate_profiles_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_affiliate_profiles_user_id'))
        batch_op.create_index(batch_op.f('ix_affiliate_profiles_user_id'), ['user_id'], unique=False)
        batch_op.drop_index(batch_op.f('ix_affiliate_profiles_ctv_code'))
        batch_op.create_index(batch_op.f('ix_affiliate_profiles_ctv_code'), ['ctv_code'], unique=False)
        batch_op.create_unique_constraint(batch_op.f('affiliate_profiles_user_id_key'), ['user_id'], postgresql_nulls_not_distinct=False)
        batch_op.create_unique_constraint(batch_op.f('affiliate_profiles_ctv_code_key'), ['ctv_code'], postgresql_nulls_not_distinct=False)
        batch_op.alter_column('updated_at',
               nullable=True,
               existing_server_default=sa.text('now()'))
        batch_op.alter_column('created_at',
               nullable=True,
               existing_server_default=sa.text('now()'))

    # ### end Alembic commands ###
