"""add_seo_fields_to_articles

Revision ID: c1d32faf40b8
Revises: 555c317a0043
Create Date: 2026-03-05 05:41:45.181129

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c1d32faf40b8'
down_revision: Union[str, Sequence[str], None] = '555c317a0043'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('articles', sa.Column('seo_title', sa.String(), nullable=True))
    op.add_column('articles', sa.Column('seo_description', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('articles', 'seo_description')
    op.drop_column('articles', 'seo_title')
    # ### end Alembic commands ###
