"""Add analysis_report to ContentCampaign CNS V87

Revision ID: c504a40ccdd3
Revises: 106081ae8dbf
Create Date: 2026-04-24 06:51:20.736606

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c504a40ccdd3'
down_revision: Union[str, Sequence[str], None] = '106081ae8dbf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('content_campaigns', schema=None) as batch_op:
        batch_op.add_column(sa.Column('analysis_report', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('content_campaigns', schema=None) as batch_op:
        batch_op.drop_column('analysis_report')

    # ### end Alembic commands ###
