"""create system_otps table

Revision ID: c8d9e1f2a3b4
Revises: b7c8d9e1f2a3
Create Date: 2026-04-12 14:19:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c8d9e1f2a3b4'
down_revision: Union[str, None] = 'b7c8d9e1f2a3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('system_otps',
        sa.Column('id', sa.String(), nullable=False),
        sa.Column('identifier', sa.String(), nullable=False),
        sa.Column('code', sa.String(length=10), nullable=False),
        sa.Column('token', sa.String(length=255), nullable=False),
        sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
        sa.Column('used_at', sa.DateTime(timezone=True), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
        sa.Column('tenant_id', sa.String(), nullable=False),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_sys_otp_identifier_token', 'system_otps', ['identifier', 'token'], unique=False)
    op.create_index(op.f('ix_system_otps_identifier'), 'system_otps', ['identifier'], unique=False)
    op.create_index(op.f('ix_system_otps_token'), 'system_otps', ['token'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_system_otps_token'), table_name='system_otps')
    op.drop_index(op.f('ix_system_otps_identifier'), table_name='system_otps')
    op.drop_index('ix_sys_otp_identifier_token', table_name='system_otps')
    op.drop_table('system_otps')
    # ### end Alembic commands ###
