"""add is_public to media_registry

Revision ID: c9927d9a523b
Revises: 0bd3805cd8a3
Create Date: 2026-03-15 22:44:28.930209

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c9927d9a523b'
down_revision: Union[str, Sequence[str], None] = '0bd3805cd8a3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('media_registry', sa.Column('is_public', sa.Boolean(), server_default=sa.text('true'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('media_registry', 'is_public')
    # ### end Alembic commands ###
