"""thiet_quan_luat_add_phone_to_users

Revision ID: d15060915579
Revises: 9a1bad71b605
Create Date: 2026-04-04 14:31:49.847068

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd15060915579'
down_revision: Union[str, Sequence[str], None] = '9a1bad71b605'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('phone', sa.String(), nullable=True))
        batch_op.create_index(batch_op.f('ix_users_phone'), ['phone'], unique=False)
        batch_op.create_index('ix_users_phone_tenant', ['tenant_id', 'phone', 'deleted_at'], unique=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index('ix_users_phone_tenant')
        batch_op.drop_index(batch_op.f('ix_users_phone'))
        batch_op.drop_column('phone')

    # ### end Alembic commands ###
