"""add_metadata_json_to_vouchers

Revision ID: d7e402929cea
Revises: ee857c92ddb2
Create Date: 2026-05-26 07:48:01.308906

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd7e402929cea'
down_revision: Union[str, Sequence[str], None] = 'ee857c92ddb2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vouchers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('metadata_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vouchers', schema=None) as batch_op:
        batch_op.drop_column('metadata_json')

    # ### end Alembic commands ###
