"""create_video_marketing_tables

Revision ID: da70604553ae
Revises: 2b7ff915b538
Create Date: 2026-06-16 12:49:53.185553

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'da70604553ae'
down_revision: Union[str, Sequence[str], None] = '2b7ff915b538'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('video_script_styles',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('platform', sa.String(length=20), nullable=False),
    sa.Column('hook_template', sa.Text(), nullable=False),
    sa.Column('style_instruction', sa.Text(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('video_scripts',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('product_id', sa.String(length=36), nullable=True),
    sa.Column('style_id', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('structured_script', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_by', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('tenant_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['product_bases.id'], ),
    sa.ForeignKeyConstraint(['style_id'], ['video_script_styles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('video_scripts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_video_scripts_tenant_id'), ['tenant_id'], unique=False)

    with op.batch_alter_table('seo_edges', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_seo_edges_source'))
        batch_op.drop_index(batch_op.f('ix_seo_edges_target'))

    with op.batch_alter_table('seo_nodes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_seo_nodes_entity_tenant'))
        batch_op.drop_index(batch_op.f('ix_seo_nodes_intent_type'))
        batch_op.drop_index(batch_op.f('ix_seo_nodes_pillar_tenant'), postgresql_where='(deleted_at IS NULL)')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('seo_nodes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_seo_nodes_pillar_tenant'), ['is_pillar', 'tenant_id'], unique=False, postgresql_where='(deleted_at IS NULL)')
        batch_op.create_index(batch_op.f('ix_seo_nodes_intent_type'), ['intent_type', 'tenant_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_seo_nodes_entity_tenant'), ['entity_type', 'entity_id', 'tenant_id'], unique=False)

    with op.batch_alter_table('seo_edges', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_seo_edges_target'), ['target_node_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_seo_edges_source'), ['source_node_id'], unique=False)

    with op.batch_alter_table('video_scripts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_video_scripts_tenant_id'))

    op.drop_table('video_scripts')
    op.drop_table('video_script_styles')
    # ### end Alembic commands ###
