"""Add article_metadata column for FAQ and SEO

Revision ID: db1b72b4063d
Revises: ba5acbaada22
Create Date: 2026-04-20 11:45:42.214533

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'db1b72b4063d'
down_revision: Union[str, Sequence[str], None] = 'ba5acbaada22'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # GEO 2026: Add article_metadata column to articles table
    op.add_column('articles', sa.Column('article_metadata', sa.JSON(), server_default='{}', nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('articles', 'article_metadata')
    # ### end Alembic commands ###
