"""add search_count to contentcampaign

Revision ID: dc1b7529149e
Revises: 7567818246e1
Create Date: 2026-03-09 00:03:04.489864

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dc1b7529149e'
down_revision: Union[str, Sequence[str], None] = '7567818246e1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('content_campaigns', sa.Column('search_count', sa.Integer(), server_default='0', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('content_campaigns', 'search_count')
    # ### end Alembic commands ###
