"""add_featured_image_to_article

Revision ID: dec3153f46c6
Revises: 11e257eec77c
Create Date: 2026-03-20 06:28:33.876504

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dec3153f46c6'
down_revision: Union[str, Sequence[str], None] = '11e257eec77c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('articles', sa.Column('featured_image', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('articles', 'featured_image')
    # ### end Alembic commands ###
