"""create_ads_policy_audit_logs

Revision ID: df731fe3f96e
Revises: v608_loyalty_checkin
Create Date: 2026-06-08 12:16:05.817911

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'df731fe3f96e'
down_revision: Union[str, Sequence[str], None] = 'v608_loyalty_checkin'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ads_policy_audit_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ad_group_id', sa.String(length=64), nullable=True),
    sa.Column('landing_page_url', sa.String(length=512), nullable=True),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('violations_count', sa.Integer(), nullable=False),
    sa.Column('sensitive_count', sa.Integer(), nullable=False),
    sa.Column('mismatch_count', sa.Integer(), nullable=False),
    sa.Column('low_volume_count', sa.Integer(), nullable=False),
    sa.Column('details', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ads_policy_audit_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ads_policy_audit_logs_ad_group_id'), ['ad_group_id'], unique=False)

    with op.batch_alter_table('affiliate_profiles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_affiliate_profiles_status'))
        batch_op.create_index('ix_affiliate_profiles_status', ['status', 'tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('affiliate_profiles', schema=None) as batch_op:
        batch_op.drop_index('ix_affiliate_profiles_status')
        batch_op.create_index(batch_op.f('ix_affiliate_profiles_status'), ['status'], unique=False)

    with op.batch_alter_table('ads_policy_audit_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ads_policy_audit_logs_ad_group_id'))

    op.drop_table('ads_policy_audit_logs')
    # ### end Alembic commands ###
