"""add_anti_spam_shield_columns_to_orders

Revision ID: e017ee064b11
Revises: v560_add_unaccent
Create Date: 2026-03-06 07:13:22.958723

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e017ee064b11'
down_revision: Union[str, Sequence[str], None] = 'v560_add_unaccent'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('is_spam', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('orders', sa.Column('spam_score', sa.Float(), server_default='0.0', nullable=False))
    op.add_column('orders', sa.Column('fingerprint', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'fingerprint')
    op.drop_column('orders', 'spam_score')
    op.drop_column('orders', 'is_spam')
    # ### end Alembic commands ###
