"""add_voucher_category_default_priority

Revision ID: e56cc76fcb74
Revises: c00199c6d798
Create Date: 2026-04-19 20:22:55.400963

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e56cc76fcb74'
down_revision: Union[str, Sequence[str], None] = 'c00199c6d798'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vouchers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('category', sa.String(), nullable=False, server_default='DISCOUNT'))
        batch_op.add_column(sa.Column('is_default', sa.Boolean(), nullable=False, server_default='false'))
        batch_op.add_column(sa.Column('priority', sa.Integer(), nullable=False, server_default='0'))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vouchers', schema=None) as batch_op:
        batch_op.drop_column('priority')
        batch_op.drop_column('is_default')
        batch_op.drop_column('category')

    # ### end Alembic commands ###
