"""add_seo_keywords_and_og_image

Revision ID: e90554f97066
Revises: v568_add_media_post_tracking
Create Date: 2026-03-23 02:25:53.244102

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e90554f97066'
down_revision: Union[str, Sequence[str], None] = 'v568_add_media_post_tracking'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('articles', sa.Column('seo_keywords', sa.String(), nullable=True))
    op.add_column('articles', sa.Column('seo_og_image', sa.String(), nullable=True))
    op.create_index(op.f('ix_media_registry_linked_post_id'), 'media_registry', ['linked_post_id'], unique=False)
    op.create_index(op.f('ix_media_registry_linked_post_type'), 'media_registry', ['linked_post_type'], unique=False)
    op.alter_column('product_bases', 'description',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('product_bases', 'description',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.drop_index(op.f('ix_media_registry_linked_post_type'), table_name='media_registry')
    op.drop_index(op.f('ix_media_registry_linked_post_id'), table_name='media_registry')
    op.drop_column('articles', 'seo_og_image')
    op.drop_column('articles', 'seo_keywords')
    # ### end Alembic commands ###
