"""add_landing_page_url_v26

Revision ID: e9b07d35313a
Revises: 972ea4561203
Create Date: 2026-05-12 11:48:00.103563

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e9b07d35313a'
down_revision: Union[str, Sequence[str], None] = '972ea4561203'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('google_ads_campaign_logs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('landing_page_url', sa.String(length=512), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('google_ads_campaign_logs', schema=None) as batch_op:
        batch_op.drop_column('landing_page_url')

    # ### end Alembic commands ###
