"""add support knowledge table

Revision ID: ed244f9f3d90
Revises: 8563cdd22c16
Create Date: 2026-04-02 15:53:03.424718

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ed244f9f3d90'
down_revision: Union[str, Sequence[str], None] = '8563cdd22c16'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('support_knowledge',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=False),
    sa.Column('question', sa.Text(), nullable=False),
    sa.Column('answer', sa.Text(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('tags', sa.JSON(), nullable=True),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('tenant_id', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('support_knowledge', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_support_knowledge_category'), ['category'], unique=False)
        batch_op.create_index(batch_op.f('ix_support_knowledge_is_active'), ['is_active'], unique=False)
        batch_op.create_index('ix_support_knowledge_tenant_active', ['tenant_id', 'is_active'], unique=False)
        batch_op.create_index(batch_op.f('ix_support_knowledge_tenant_id'), ['tenant_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('support_knowledge', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_support_knowledge_tenant_id'))
        batch_op.drop_index('ix_support_knowledge_tenant_active')
        batch_op.drop_index(batch_op.f('ix_support_knowledge_is_active'))
        batch_op.drop_index(batch_op.f('ix_support_knowledge_category'))

    op.drop_table('support_knowledge')
    # ### end Alembic commands ###
