"""auto_sync_media_registry_and_support

Revision ID: ee857c92ddb2
Revises: 7a5bcc5b8068
Create Date: 2026-05-22 13:24:10.401620

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ee857c92ddb2'
down_revision: Union[str, Sequence[str], None] = '7a5bcc5b8068'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('media_registry', schema=None) as batch_op:
        batch_op.create_index('ix_media_campaign_provider', ['campaign_id', 'provider'], unique=False)
        batch_op.create_index('ix_media_is_linked', ['tenant_id', 'is_linked'], unique=False)
        batch_op.create_index(batch_op.f('ix_media_registry_campaign_id'), ['campaign_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_media_registry_filename'), ['filename'], unique=False)
        batch_op.create_index(batch_op.f('ix_media_registry_is_linked'), ['is_linked'], unique=False)
        batch_op.create_index(batch_op.f('ix_media_registry_owner_id'), ['owner_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_media_registry_tenant_id'), ['tenant_id'], unique=False)
        batch_op.create_index('ix_media_tenant_deleted', ['tenant_id', 'deleted_at'], unique=False)
        batch_op.create_unique_constraint(None, ['file_path'])
        batch_op.create_foreign_key(None, 'content_campaigns', ['campaign_id'], ['id'], ondelete='SET NULL')
        batch_op.create_foreign_key(None, 'users', ['owner_id'], ['id'], ondelete='SET NULL')

    with op.batch_alter_table('media_usage', schema=None) as batch_op:
        batch_op.create_index('ix_media_usage_asset_entity', ['asset_id', 'entity_type', 'entity_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_media_usage_asset_id'), ['asset_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_media_usage_entity_id'), ['entity_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_media_usage_entity_type'), ['entity_type'], unique=False)
        batch_op.create_index('ix_media_usage_lookup', ['entity_type', 'entity_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_media_usage_tenant_id'), ['tenant_id'], unique=False)
        batch_op.create_foreign_key(None, 'media_registry', ['asset_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('media_usage', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_media_usage_tenant_id'))
        batch_op.drop_index('ix_media_usage_lookup')
        batch_op.drop_index(batch_op.f('ix_media_usage_entity_type'))
        batch_op.drop_index(batch_op.f('ix_media_usage_entity_id'))
        batch_op.drop_index(batch_op.f('ix_media_usage_asset_id'))
        batch_op.drop_index('ix_media_usage_asset_entity')

    with op.batch_alter_table('media_registry', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_index('ix_media_tenant_deleted')
        batch_op.drop_index(batch_op.f('ix_media_registry_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_media_registry_owner_id'))
        batch_op.drop_index(batch_op.f('ix_media_registry_is_linked'))
        batch_op.drop_index(batch_op.f('ix_media_registry_filename'))
        batch_op.drop_index(batch_op.f('ix_media_registry_campaign_id'))
        batch_op.drop_index('ix_media_is_linked')
        batch_op.drop_index('ix_media_campaign_provider')

    # ### end Alembic commands ###
