"""THIET_QUAN_LUAT_HARDENING

Revision ID: eea58dee8ce0
Revises: e5848d9ad7e0
Create Date: 2026-03-03 18:04:24.416795

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eea58dee8ce0'
down_revision: Union[str, Sequence[str], None] = 'e5848d9ad7e0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('agent_telemetry_logs', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False))
    op.create_index(op.f('ix_agent_telemetry_logs_tenant_id'), 'agent_telemetry_logs', ['tenant_id'], unique=False)
    op.create_index('ix_articles_tenant_deleted', 'articles', ['tenant_id', 'deleted_at'], unique=False)
    op.create_index(op.f('ix_articles_tenant_id'), 'articles', ['tenant_id'], unique=False)
    op.create_index('ix_categories_tenant_deleted', 'categories', ['tenant_id', 'deleted_at'], unique=False)
    op.create_index(op.f('ix_categories_tenant_id'), 'categories', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_chat_messages_tenant_id'), 'chat_messages', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_drafts_tenant_id'), 'drafts', ['tenant_id'], unique=False)
    op.add_column('notifications', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False))
    op.create_index(op.f('ix_notifications_tenant_id'), 'notifications', ['tenant_id'], unique=False)
    op.create_index('ix_orders_tenant_deleted', 'orders', ['tenant_id', 'deleted_at'], unique=False)
    op.create_index(op.f('ix_orders_tenant_id'), 'orders', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_product_bases_tenant_id'), 'product_bases', ['tenant_id'], unique=False)
    op.create_index('ix_products_tenant_deleted', 'product_bases', ['tenant_id', 'deleted_at'], unique=False)
    op.create_index('ix_roles_tenant_deleted', 'roles', ['tenant_id', 'deleted_at'], unique=False)
    op.create_index(op.f('ix_roles_tenant_id'), 'roles', ['tenant_id'], unique=False)
    op.create_index('ix_users_tenant_deleted', 'users', ['tenant_id', 'deleted_at'], unique=False)
    op.create_index(op.f('ix_users_tenant_id'), 'users', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_tenant_id'), table_name='users')
    op.drop_index('ix_users_tenant_deleted', table_name='users')
    op.drop_index(op.f('ix_roles_tenant_id'), table_name='roles')
    op.drop_index('ix_roles_tenant_deleted', table_name='roles')
    op.drop_index('ix_products_tenant_deleted', table_name='product_bases')
    op.drop_index(op.f('ix_product_bases_tenant_id'), table_name='product_bases')
    op.drop_index(op.f('ix_orders_tenant_id'), table_name='orders')
    op.drop_index('ix_orders_tenant_deleted', table_name='orders')
    op.drop_index(op.f('ix_notifications_tenant_id'), table_name='notifications')
    op.drop_column('notifications', 'updated_at')
    op.drop_index(op.f('ix_drafts_tenant_id'), table_name='drafts')
    op.drop_index(op.f('ix_chat_messages_tenant_id'), table_name='chat_messages')
    op.drop_index(op.f('ix_categories_tenant_id'), table_name='categories')
    op.drop_index('ix_categories_tenant_deleted', table_name='categories')
    op.drop_index(op.f('ix_articles_tenant_id'), table_name='articles')
    op.drop_index('ix_articles_tenant_deleted', table_name='articles')
    op.drop_index(op.f('ix_agent_telemetry_logs_tenant_id'), table_name='agent_telemetry_logs')
    op.drop_column('agent_telemetry_logs', 'updated_at')
    # ### end Alembic commands ###
