"""Add mobile_images to product_bases

Revision ID: fb9ad52c5e5a
Revises: fb79dda5d643
Create Date: 2026-04-02 22:33:09.118952

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fb9ad52c5e5a'
down_revision: Union[str, Sequence[str], None] = 'fb79dda5d643'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    from sqlalchemy.dialects import postgresql
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product_bases', sa.Column('mobile_images', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('product_bases', 'mobile_images')
    # ### end Alembic commands ###
