"""v608: Add checkin fields to UserLoyalty

Revision ID: v608_loyalty_checkin
Revises: v607
Create Date: 2026-05-31

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'v608_loyalty_checkin'
down_revision: Union[str, Sequence[str], None] = 'v607'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_loyalty', sa.Column('current_checkin_streak', sa.Integer(), nullable=True))
    op.add_column('user_loyalty', sa.Column('last_checkin_date', sa.DateTime(timezone=True), nullable=True))
    # Provide default values and set not null if required, though mapped_column default is 0 for streak
    op.execute("UPDATE user_loyalty SET current_checkin_streak = 0 WHERE current_checkin_streak IS NULL")
    op.alter_column('user_loyalty', 'current_checkin_streak', nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_loyalty', 'last_checkin_date')
    op.drop_column('user_loyalty', 'current_checkin_streak')
    # ### end Alembic commands ###
